/**
 * Haseen UI — Theme Definitions
 *
 * Light and dark theme token maps using CSS custom properties.
 * All semantic tokens resolve to palette primitives + opacities.
 */

import { opacities, palette } from '../tokens';

const o = opacities;
const c = palette;

const misc = {
  '--hsn-primary-button-hover-shadow': '0 1px 0 rgba(27, 31, 35, 0.1)',
  '--hsn-primary-button-hover-inset-shadow': 'inset 0 1px 0 hsla(0, 0%, 100%, 0.03)',
  '--hsn-code-mark-color': `rgb(${c.teal500})`,
  '--hsn-code-mark-bg': `rgba(${c.black}, ${o[6]})`,
};

export interface ThemeTokens {
  [key: string]: string;
}

export interface ThemeSet {
  light: ThemeTokens;
  dark: ThemeTokens;
}

const colorVars = {
  '--hsn-white': c.white,
  '--hsn-black': c.black,
  '--hsn-grey-100': c.grey100,
  '--hsn-grey-200': c.grey200,
  '--hsn-grey-300': c.grey300,
  '--hsn-grey-400': c.grey400,
  '--hsn-grey-500': c.grey500,
  '--hsn-grey-600': c.grey600,
  '--hsn-grey-700': c.grey700,
  '--hsn-grey-800': c.grey800,
  '--hsn-grey-900': c.grey900,
  '--hsn-teal-100': c.teal100,
  '--hsn-teal-200': c.teal200,
  '--hsn-teal-300': c.teal300,
  '--hsn-teal-400': c.teal400,
  '--hsn-teal-500': c.teal500,
  '--hsn-teal-600': c.teal600,
  '--hsn-teal-700': c.teal700,
  '--hsn-teal-800': c.teal800,
  '--hsn-green-100': c.green100,
  '--hsn-green-200': c.green200,
  '--hsn-green-300': c.green300,
  '--hsn-green-400': c.green400,
  '--hsn-green-500': c.green500,
  '--hsn-green-600': c.green600,
  '--hsn-green-700': c.green700,
  '--hsn-green-800': c.green800,
  '--hsn-red-100': c.red100,
  '--hsn-red-200': c.red200,
  '--hsn-red-300': c.red300,
  '--hsn-red-400': c.red400,
  '--hsn-red-500': c.red500,
  '--hsn-red-600': c.red600,
  '--hsn-red-700': c.red700,
  '--hsn-red-800': c.red800,
  '--hsn-orange-100': c.orange100,
  '--hsn-orange-200': c.orange200,
  '--hsn-orange-300': c.orange300,
  '--hsn-orange-400': c.orange400,
  '--hsn-orange-500': c.orange500,
  '--hsn-orange-600': c.orange600,
  '--hsn-orange-700': c.orange700,
  '--hsn-orange-800': c.orange800,
  '--hsn-yellow-100': c.yellow100,
  '--hsn-yellow-200': c.yellow200,
  '--hsn-yellow-300': c.yellow300,
  '--hsn-yellow-400': c.yellow400,
  '--hsn-yellow-500': c.yellow500,
  '--hsn-yellow-600': c.yellow600,
  '--hsn-yellow-700': c.yellow700,
  '--hsn-yellow-800': c.yellow800,
  '--hsn-blue-100': c.blue100,
  '--hsn-blue-200': c.blue200,
  '--hsn-blue-300': c.blue300,
  '--hsn-blue-400': c.blue400,
  '--hsn-blue-500': c.blue500,
  '--hsn-blue-600': c.blue600,
  '--hsn-blue-700': c.blue700,
  '--hsn-blue-800': c.blue800,
  '--hsn-pink-100': c.pink100,
  '--hsn-pink-200': c.pink200,
  '--hsn-pink-300': c.pink300,
  '--hsn-pink-400': c.pink400,
  '--hsn-pink-500': c.pink500,
  '--hsn-pink-600': c.pink600,
  '--hsn-pink-700': c.pink700,
  '--hsn-pink-800': c.pink800,
  '--hsn-indigo-100': c.indigo100,
  '--hsn-indigo-200': c.indigo200,
  '--hsn-indigo-300': c.indigo300,
  '--hsn-indigo-400': c.indigo400,
  '--hsn-indigo-500': c.indigo500,
  '--hsn-indigo-600': c.indigo600,
  '--hsn-indigo-700': c.indigo700,
  '--hsn-indigo-800': c.indigo800,
};

const theme: ThemeSet = {
  light: {
    ...colorVars,
    ...misc,
    // ── Text ──
    '--hsn-text-primary': `rgb(${c.grey900})`,
    '--hsn-text-secondary': `rgba(${c.black}, ${o[56]})`,
    '--hsn-text-tertiary': `rgba(${c.black}, ${o[42]})`,
    '--hsn-text-disabled': `rgba(${c.black}, ${o[32]})`,
    '--hsn-text-always-white': `rgb(${c.white})`,
    '--hsn-text-always-black': `rgb(${c.black})`,
    '--hsn-text-link': `rgb(${c.teal600})`,
    '--hsn-text-destructive': `rgb(${c.red600})`,
    '--hsn-text-inverse': `rgb(${c.white})`,
    // ── Icon ──
    '--hsn-icon-primary': `rgb(${c.grey900})`,
    '--hsn-icon-secondary': `rgba(${c.black}, ${o[56]})`,
    '--hsn-icon-tertiary': `rgba(${c.black}, ${o[42]})`,
    '--hsn-icon-disabled': `rgba(${c.black}, ${o[32]})`,
    '--hsn-icon-always-white': `rgb(${c.white})`,
    '--hsn-icon-always-black': `rgb(${c.black})`,
    '--hsn-icon-link': `rgb(${c.teal600})`,
    '--hsn-icon-destructive': `rgb(${c.red600})`,
    '--hsn-icon-inverse': `rgb(${c.white})`,
    // ── CTA / Button ──
    '--hsn-cta-primary-default': `rgb(${c.teal500})`,
    '--hsn-cta-primary-hover': `rgb(${c.teal600})`,
    '--hsn-cta-primary-active': `rgb(${c.teal700})`,
    '--hsn-cta-primary-disabled': `rgba(${c.teal500}, ${o[32]})`,
    '--hsn-cta-secondary-default': `rgb(${c.white})`,
    '--hsn-cta-secondary-hover': `rgba(${c.black}, ${o[6]})`,
    '--hsn-cta-secondary-active': `rgba(${c.black}, ${o[8]})`,
    '--hsn-cta-secondary-disabled': 'transparent',
    '--hsn-cta-tertiary-default': 'transparent',
    '--hsn-cta-tertiary-hover': `rgba(${c.black}, ${o[8]})`,
    '--hsn-cta-tertiary-active': `rgba(${c.black}, ${o[10]})`,
    '--hsn-cta-tertiary-disabled': 'transparent',
    '--hsn-cta-destructive-default': 'transparent',
    '--hsn-cta-destructive-hover': `rgba(${c.red600}, ${o[8]})`,
    '--hsn-cta-destructive-active': `rgba(${c.red600}, ${o[12]})`,
    '--hsn-cta-destructive-disabled': 'transparent',
    '--hsn-cta-chip-default': 'transparent',
    '--hsn-cta-chip-hover': `rgba(${c.black}, ${o[6]})`,
    '--hsn-cta-navigation-default': 'transparent',
    '--hsn-cta-navigation-hover': `rgba(${c.black}, ${o[6]})`,
    '--hsn-cta-navigation-active': `rgba(${c.black}, ${o[12]})`,
    '--hsn-cta-navigation-disabled': 'transparent',
    // ── Border ──
    '--hsn-border-primary': `rgba(${c.black}, ${o[12]})`,
    '--hsn-border-secondary': `rgba(${c.black}, ${o[8]})`,
    '--hsn-border-tertiary': `rgba(${c.black}, ${o[4]})`,
    '--hsn-border-hover': `rgba(${c.black}, ${o[48]})`,
    '--hsn-border-active': `rgb(${c.teal500})`,
    '--hsn-border-destructive': `rgba(${c.red600}, ${o[12]})`,
    // ── Background ──
    '--hsn-bg-main-container': `linear-gradient(0deg, rgba(${c.black}, ${o[2]}), rgba(${c.black}, ${o[2]})), rgb(${c.white})`,
    '--hsn-bg-sidepanel': `linear-gradient(0deg, rgba(${c.black}, ${o[4]}), rgba(${c.black}, ${o[4]})), rgb(${c.white})`,
    '--hsn-bg-l0-solid': `linear-gradient(0deg, rgba(${c.black}, ${o[4]}), rgba(${c.black}, ${o[4]})), rgb(${c.white})`,
    '--hsn-bg-l0-glass': `rgba(245, 245, 245, ${o[72]})`,
    '--hsn-bg-l1-solid': `linear-gradient(0deg, rgba(${c.black}, ${o[2]}), rgba(${c.black}, ${o[2]})), rgb(${c.white})`,
    '--hsn-bg-l1-glass': `rgba(${c.white}, ${o[72]})`,
    '--hsn-bg-l2-solid': `rgb(${c.white})`,
    '--hsn-bg-l2-glass': `rgba(${c.white}, ${o[72]})`,
    '--hsn-bg-l3-solid': `rgb(${c.white})`,
    '--hsn-bg-l3-glass': `rgba(${c.white}, ${o[72]})`,
    '--hsn-bg-emphasis': `rgb(${c.grey900})`,
    '--hsn-bg-scrim': `rgba(${c.white}, ${o[80]})`,
    '--hsn-bg-cell-hover': `rgba(${c.black}, ${o[6]})`,
    '--hsn-bg-cell-active': `rgba(${c.black}, ${o[8]})`,
    '--hsn-bg-field-default': `rgba(${c.black}, ${o[6]})`,
    '--hsn-bg-field-hover': `rgba(${c.black}, ${o[8]})`,
    // ── Overlay ──
    '--hsn-bg-overlay-primary': `rgba(${c.black}, ${o[10]})`,
    '--hsn-bg-overlay-secondary': `rgba(${c.black}, ${o[8]})`,
    '--hsn-bg-overlay-tertiary': `rgba(${c.black}, ${o[4]})`,
    '--hsn-bg-overlay-destructive': `rgba(${c.red400}, ${o[24]})`,
    // ── Accent ──
    '--hsn-accent-teal-primary': `rgb(${c.teal600})`,
    '--hsn-accent-teal-secondary': `rgba(${c.teal400}, ${o[36]})`,
    '--hsn-accent-green-primary': `rgb(${c.green600})`,
    '--hsn-accent-green-secondary': `rgba(${c.green400}, ${o[28]})`,
    '--hsn-accent-orange-primary': `rgb(${c.orange600})`,
    '--hsn-accent-orange-secondary': `rgba(${c.orange400}, ${o[36]})`,
    '--hsn-accent-pink-primary': `rgb(${c.pink600})`,
    '--hsn-accent-pink-secondary': `rgba(${c.pink400}, ${o[36]})`,
    '--hsn-accent-yellow-primary': `rgb(${c.yellow600})`,
    '--hsn-accent-yellow-secondary': `rgba(${c.yellow400}, ${o[48]})`,
    '--hsn-accent-blue-primary': `rgb(${c.blue600})`,
    '--hsn-accent-blue-secondary': `rgba(${c.blue400}, ${o[36]})`,
    '--hsn-accent-red-primary': `rgb(${c.red600})`,
    '--hsn-accent-red-secondary': `rgba(${c.red400}, ${o[36]})`,
    '--hsn-accent-indigo-primary': `rgb(${c.indigo600})`,
    '--hsn-accent-indigo-secondary': `rgba(${c.indigo400}, ${o[36]})`,
    // ── Shadows ──
    '--hsn-shadow-l1': '0px 1px 3px rgba(0, 0, 0, 0.1), 0px 0px 2px rgba(0, 0, 0, 0.06)',
    '--hsn-shadow-l2': '0px 10px 15px -3px rgba(0, 0, 0, 0.1), 0px 4px 6px -2px rgba(0, 0, 0, 0.05)',
    '--hsn-shadow-l3': '0px 25px 50px -12px rgba(0, 0, 0, 0.25)',
    '--hsn-shadow-inset': 'inset 1px 1px 0px rgba(0, 0, 0, 0.1)',
    '--hsn-shadow-secondary-button': 'inset 0px 1px 0px rgba(0, 0, 0, 0.1), inset 0px -1px 0px 1px rgba(0, 0, 0, 0.1)',
    '--hsn-shadow-destructive-button': 'inset 0px -1px 0px 1px rgba(220, 38, 38, 0.2), inset 0px 1px 0px rgba(220, 38, 38, 0.2)',
    '--hsn-shadow-dropdown': 'rgba(27, 31, 35, 0.04) 0 1px 0, rgba(255, 255, 255, 0.25) 0 2px 0 inset',
    '--hsn-shadow-drawer': '0px 0px 40px rgba(0, 0, 0, 0.1)',
    // ── Misc ──
    '--hsn-bg-cell-unread': `rgb(${c.white})`,
    '--hsn-status-bar-color': `linear-gradient(0deg, rgba(${c.black}, ${o[2]}), rgba(${c.black}, ${o[2]})), rgb(${c.white})`,
    '--hsn-illustration-fill': `rgb(${c.grey100})`,
  },
  dark: {
    ...colorVars,
    ...misc,
    // ── Text ──
    '--hsn-text-primary': `rgb(${c.white})`,
    '--hsn-text-secondary': `rgba(${c.white}, ${o[54]})`,
    '--hsn-text-tertiary': `rgba(${c.white}, ${o[42]})`,
    '--hsn-text-disabled': `rgba(${c.white}, ${o[28]})`,
    '--hsn-text-always-white': `rgb(${c.white})`,
    '--hsn-text-always-black': `rgb(${c.black})`,
    '--hsn-text-link': `rgb(${c.teal400})`,
    '--hsn-text-destructive': `rgb(${c.red400})`,
    '--hsn-text-inverse': `rgb(${c.black})`,
    // ── Icon ──
    '--hsn-icon-primary': `rgb(${c.white})`,
    '--hsn-icon-secondary': `rgba(${c.white}, ${o[54]})`,
    '--hsn-icon-tertiary': `rgba(${c.white}, ${o[42]})`,
    '--hsn-icon-disabled': `rgba(${c.white}, ${o[28]})`,
    '--hsn-icon-always-white': `rgb(${c.white})`,
    '--hsn-icon-always-black': `rgb(${c.black})`,
    '--hsn-icon-link': `rgb(${c.teal400})`,
    '--hsn-icon-destructive': `rgb(${c.red400})`,
    '--hsn-icon-inverse': `rgb(${c.black})`,
    // ── CTA / Button ──
    '--hsn-cta-primary-default': `rgb(${c.teal500})`,
    '--hsn-cta-primary-hover': `rgb(${c.teal400})`,
    '--hsn-cta-primary-active': `rgb(${c.teal300})`,
    '--hsn-cta-primary-disabled': `rgba(${c.teal500}, ${o[32]})`,
    '--hsn-cta-secondary-default': `rgba(${c.white}, ${o[4]})`,
    '--hsn-cta-secondary-hover': `rgba(${c.white}, ${o[8]})`,
    '--hsn-cta-secondary-active': `rgba(${c.white}, ${o[12]})`,
    '--hsn-cta-secondary-disabled': 'transparent',
    '--hsn-cta-tertiary-default': 'transparent',
    '--hsn-cta-tertiary-hover': `rgba(${c.white}, ${o[8]})`,
    '--hsn-cta-tertiary-active': `rgba(${c.white}, ${o[10]})`,
    '--hsn-cta-tertiary-disabled': 'transparent',
    '--hsn-cta-destructive-default': `rgba(${c.white}, ${o[4]})`,
    '--hsn-cta-destructive-hover': `rgba(${c.red400}, ${o[12]})`,
    '--hsn-cta-destructive-active': `rgba(${c.red400}, ${o[16]})`,
    '--hsn-cta-destructive-disabled': 'transparent',
    '--hsn-cta-chip-default': 'transparent',
    '--hsn-cta-chip-hover': `rgba(${c.white}, ${o[8]})`,
    '--hsn-cta-navigation-default': 'transparent',
    '--hsn-cta-navigation-hover': `rgba(${c.white}, ${o[8]})`,
    '--hsn-cta-navigation-active': `rgba(${c.white}, ${o[12]})`,
    '--hsn-cta-navigation-disabled': 'transparent',
    // ── Border ──
    '--hsn-border-primary': `rgba(${c.white}, ${o[12]})`,
    '--hsn-border-secondary': `rgba(${c.white}, ${o[8]})`,
    '--hsn-border-tertiary': `rgba(${c.white}, ${o[4]})`,
    '--hsn-border-hover': `rgba(${c.white}, ${o[48]})`,
    '--hsn-border-active': `rgb(${c.teal400})`,
    '--hsn-border-destructive': `rgba(${c.red400}, ${o[12]})`,
    // ── Background ──
    '--hsn-bg-main-container': `linear-gradient(0deg, rgba(${c.white}, ${o[12]}), rgba(${c.white}, ${o[12]})), rgb(${c.black})`,
    '--hsn-bg-sidepanel': `linear-gradient(0deg, rgba(${c.white}, ${o[10]}), rgba(${c.white}, ${o[10]})), rgb(${c.black})`,
    '--hsn-bg-l0-solid': `linear-gradient(0deg, rgba(${c.white}, ${o[8]}), rgba(${c.white}, ${o[8]})), rgb(${c.black})`,
    '--hsn-bg-l0-glass': `rgba(10, 10, 10, ${o[72]})`,
    '--hsn-bg-l1-solid': `linear-gradient(0deg, rgba(${c.white}, ${o[10]}), rgba(${c.white}, ${o[10]})), rgb(${c.black})`,
    '--hsn-bg-l1-glass': `rgba(20, 20, 20, ${o[72]})`,
    '--hsn-bg-l2-solid': `linear-gradient(0deg, rgba(${c.white}, ${o[12]}), rgba(${c.white}, ${o[12]})), rgb(${c.black})`,
    '--hsn-bg-l2-glass': `rgba(31, 31, 31, ${o[72]})`,
    '--hsn-bg-l3-solid': `linear-gradient(0deg, rgba(${c.white}, ${o[14]}), rgba(${c.white}, ${o[14]})), rgb(${c.black})`,
    '--hsn-bg-l3-glass': `rgba(41, 41, 41, ${o[72]})`,
    '--hsn-bg-emphasis': `rgb(${c.grey800})`,
    '--hsn-bg-scrim': `rgba(${c.black}, ${o[42]})`,
    '--hsn-bg-cell-hover': `rgba(${c.white}, ${o[6]})`,
    '--hsn-bg-cell-active': `rgba(${c.white}, ${o[8]})`,
    '--hsn-bg-field-default': `rgba(${c.white}, ${o[8]})`,
    '--hsn-bg-field-hover': `rgba(${c.white}, ${o[12]})`,
    // ── Overlay ──
    '--hsn-bg-overlay-primary': `rgba(${c.white}, ${o[10]})`,
    '--hsn-bg-overlay-secondary': `rgba(${c.white}, ${o[8]})`,
    '--hsn-bg-overlay-tertiary': `rgba(${c.white}, ${o[4]})`,
    '--hsn-bg-overlay-destructive': `rgba(${c.red400}, ${o[24]})`,
    // ── Accent ──
    '--hsn-accent-teal-primary': `rgba(${c.teal400}, ${o[88]})`,
    '--hsn-accent-teal-secondary': `rgba(${c.teal400}, ${o[36]})`,
    '--hsn-accent-green-primary': `rgba(${c.green400}, ${o[88]})`,
    '--hsn-accent-green-secondary': `rgba(${c.green400}, ${o[32]})`,
    '--hsn-accent-orange-primary': `rgba(${c.orange400}, ${o[88]})`,
    '--hsn-accent-orange-secondary': `rgba(${c.orange400}, ${o[36]})`,
    '--hsn-accent-pink-primary': `rgba(${c.pink400}, ${o[88]})`,
    '--hsn-accent-pink-secondary': `rgba(${c.pink400}, ${o[36]})`,
    '--hsn-accent-yellow-primary': `rgba(${c.yellow400}, ${o[88]})`,
    '--hsn-accent-yellow-secondary': `rgba(${c.yellow400}, ${o[36]})`,
    '--hsn-accent-blue-primary': `rgba(${c.blue400}, ${o[88]})`,
    '--hsn-accent-blue-secondary': `rgba(${c.blue400}, ${o[36]})`,
    '--hsn-accent-red-primary': `rgba(${c.red400}, ${o[88]})`,
    '--hsn-accent-red-secondary': `rgba(${c.red400}, ${o[36]})`,
    '--hsn-accent-indigo-primary': `rgba(${c.indigo400}, ${o[88]})`,
    '--hsn-accent-indigo-secondary': `rgba(${c.indigo400}, ${o[36]})`,
    // ── Shadows ──
    '--hsn-shadow-l1': '0px 1px 3px rgba(0, 0, 0, 0.3), 0px 1px 2px rgba(0, 0, 0, 0.26)',
    '--hsn-shadow-l2': '0px 10px 15px -3px rgba(0, 0, 0, 0.3), 0px 4px 6px -2px rgba(0, 0, 0, 0.25)',
    '--hsn-shadow-l3': '0px 25px 50px -12px rgba(0, 0, 0, 0.55)',
    '--hsn-shadow-inset': 'inset 0px -1px 0px rgba(255, 255, 255, 0.1)',
    '--hsn-shadow-secondary-button': 'inset 0px 1px 0px rgb(255 255 255 / 20%), inset 0px -1px 0px 1px hsl(0deg 0% 100% / 20%)',
    '--hsn-shadow-destructive-button': 'inset 0px -1px 0px 1px rgba(248, 113, 113, 0.12), inset 0px 1px 0px rgba(248, 113, 113, 0.12)',
    '--hsn-shadow-dropdown': 'rgba(27, 31, 35, 0.04) 0 1px 0, rgba(255, 255, 255, 0.25) 0 2px 0 inset',
    '--hsn-shadow-drawer': '0px 0px 40px rgba(0, 0, 0, 0.1)',
    // ── Misc ──
    '--hsn-bg-cell-unread': `linear-gradient(0deg, rgba(${c.white}, ${o[14]}), rgba(${c.white}, ${o[14]})), rgb(${c.black})`,
    '--hsn-status-bar-color': `linear-gradient(0deg, rgba(${c.white}, ${o[12]}), rgba(${c.white}, ${o[12]})), rgb(${c.black})`,
    '--hsn-illustration-fill': `rgb(${c.grey800})`,
  },
};

export const themeNames = theme;
